version: '3.9'

services:
  nginx-proxy-manager:
    image: 'docker.io/jc21/nginx-proxy-manager:latest'
    container_name: nginx-proxy-manager
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    networks:
      - shared
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt

  it-tools:
    image: corentinth/it-tools:latest
    container_name: it-tools
    restart: unless-stopped
    ports:
      - '8090:80'
    networks:
      - shared
    volumes:
      - it-volume:/app/data

networks:
  shared:
    driver: bridge

volumes:
  it-volume:
